project:
  type: website
  output-dir: docs

website:
  title: "AmazingAthena"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/athenafm/
      #- icon: twitter
      ## Use your own social media link
      #  href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

comments:
  giscus:
    repo: athenafm/AmazingAthena

execute:
  freeze: true